### ISSUE TITLE
Clicking on Search Result sdss_id Resets Login in new page

### ISSUE THREAD

**Issue by zachway1996** [sdss/zora#15]
After searching for targets using the main search page, clicking on an sdss_id link will bring up a new page with the sdss_id target information. Within this new page, however, my session is logged out and defaults to DR18.

**Comment by havok2063** [comment]
This is due to the fact that the Pinia store only persists in-memory within the app, and when you open in a new tab, a instance of the application is created.  Thus the pinia store does not persist among new tabs or page loads.  this is a feature of pinia but there are plugins for pinia that allow for a more persistent storage using a browser `LocalStorage` or `SessionStorage`.
